// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhbltZ8SfEXLLQj-mVAVppdNCN3dVUHuo',
    appId: '1:699057576920:web:167985284809370b8c30ad',
    messagingSenderId: '699057576920',
    projectId: 'todify-11303',
    authDomain: 'todify-11303.firebaseapp.com',
    storageBucket: 'todify-11303.appspot.com',
    measurementId: 'G-JJJ8CDKZZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK9zO3AoJfctnYG92BM11zM_AIA_BfnoE',
    appId: '1:699057576920:android:6a192e0a096554f38c30ad',
    messagingSenderId: '699057576920',
    projectId: 'todify-11303',
    storageBucket: 'todify-11303.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7TARf9wZAHOPWokTCIMEX0ei_u-09twE',
    appId: '1:699057576920:ios:ee824b7c57d7d8338c30ad',
    messagingSenderId: '699057576920',
    projectId: 'todify-11303',
    storageBucket: 'todify-11303.appspot.com',
    iosBundleId: 'com.example.todoFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhbltZ8SfEXLLQj-mVAVppdNCN3dVUHuo',
    appId: '1:699057576920:web:596100f6be54643f8c30ad',
    messagingSenderId: '699057576920',
    projectId: 'todify-11303',
    authDomain: 'todify-11303.firebaseapp.com',
    storageBucket: 'todify-11303.appspot.com',
    measurementId: 'G-VY53EY72GB',
  );
}
